import os
import pathlib


env = Environment(
    tools=("gcc", "g++", "gnulink", "ar", "as"),
    CC="C:/DGSTC/MINGW32/bin/gcc",
    ENV=os.environ,
)


paths = [
    ".",
    "../src",
    "../json-maker/src/include/json-maker",
    "../json-maker/src/include",
    "../json-maker/src"
]


env.Append(CPPPATH=paths)

sources = []

for path in paths:
    for file in pathlib.Path(path).glob("*.c"):
        sources.append(str(file))

env.Program(target="test.exe", source=sources)
